services:
  postgres:
    image: postgres:16.3
    container_name: postgres_test
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    ports:
      - "${DB_PORT}:5432"
    command:
      - postgres
      - -c
      - max_connections=1000
      - -c
      - shared_buffers=1GB
      - -c
      - work_mem=8MB
      - -c
      - max_parallel_workers=4
      - -c
      - parallel_tuple_cost=0.05
      - -c
      - effective_cache_size=2GB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend

  app:
    build: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      NODE_ENV: development
    depends_on:
      - postgres
    expose:
      - 3000
    networks:
      - backend

  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
