export enum ExceptionEnum {
  INVALID_USERID_INPUT = 'INVALID_USERID_INPUT',
  INVALID_AMOUNT_INPUT = 'INVALID_AMOUNT_INPUT',
  INSUFFICIENT_FUNDS_OR_USER_NOT_FOUND = 'INSUFFICIENT_FUNDS_OR_USER_NOT_FOUND',
}
